#!/bin/bash                                                                                                                                         
echo '#include <stdio.h>' > "$1"
echo '' >> "$1"
echo '/**' >> "$1"
echo ' * main - Entry point' >> "$1"
echo ' *' >> "$1"
echo ' * Return: Always 0 (Success)' >> "$1"
echo '*/' >> "$1"
echo '' >> "$1"
echo 'int main(void)' >> "$1"
echo '{' >> "$1"
echo 'return (0);' >> "$1"
echo '}' >> "$1"
chmod 755 "$1"
